### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by BenHerbst**
I tried nvr, and it doesnt work on windows, only on linux.

### CODE REVIEW

**Comment by BenHerbst** [comment]
Also found a workround at the end of this webpage: [https://vi.stackexchange.com/questions/5348/how-can-i-use-servername-and-remote-in-neovim]
You could mention that in the Readme.

**Comment by BenHerbst** [comment]
This would be the code to open a new tab, when a file is clicked in godot: 
`import os
import sys
import neovim


def main():
    servername_path = "servername.txt"

    if not os.path.isfile(servername_path):
        return 1

    with open(servername_path, mode="rt") as f:
        line = f.readline()
        servername = line.strip("\r\n ")

    try:
        nvim = neovim.attach("socket", path=servername)
    except Exception:
        print("Neovim not found")
        os.remove(servername_path)
        return 1

    if len(sys.argv) <= 1:
        return

    path = sys.argv[1]
    nvim.command(':tabnew %s' % path)

    nvim.close()


if __name__ == "__main__":
    ret = main()
    sys.exit(ret)
`

**Comment by paskausks** [comment]
This is no longer necessary - https://github.com/habamax/vim-godot/pull/66

**Comment by BenHerbst** [comment]
Great, I close this issue now with this comment @paskausks

**Pull request closed without merging**
